#pragma once
#include <SDL_keycode.h>
#ifdef GAMEENGINE_EXPORTS
#define GAMEENGINE_FLUIXINPUTEVENT __declspec(dllexport)
#else
#define GAMEENGINE_FLUIXINPUTEVENT __declspec(dllimport)
#endif

enum class GAMEENGINE_FLUIXINPUTEVENT FluixInputEvent {
	KEY_RETURN = SDLK_RETURN,
	KEY_BACKSPACE = SDLK_BACKSPACE,
	KEY_SPACE = SDLK_SPACE,
	SCANCODE_0 = SDL_SCANCODE_0,
	SCANCODE_ESCAPE = SDL_SCANCODE_ESCAPE,
	SCANCODE_F3 = SDL_SCANCODE_F3,
	SCANCODE_A = SDL_SCANCODE_A,
	SCANCODE_D = SDL_SCANCODE_D,
	SCANCODE_S = SDL_SCANCODE_S,
	SCANCODE_SPACE = SDL_SCANCODE_SPACE,
	SCANCODE_1 = SDL_SCANCODE_1,
	SCANCODE_2 = SDL_SCANCODE_2,
	SCANCODE_3 = SDL_SCANCODE_3
};
